name: yapc-docs
channels:
  - conda-forge
dependencies:
  - cython
  - docutils<0.18
  - future
  - graphviz
  - notebook
  - numpy
  - numpydoc
  - pip
  - python>=3.6
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - sphinx-argparse>=0.4
    - ..

